name: Deploy
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: security-check
        run: docker build -t dockerfile . && docker run --rm --pid=host dockerfile
      - name: Deploy
        env: 
          DEP_PATH: "requirenments.txt"
          HEROKU_API_KEY: ${{secrets.HEROKU_API_KEY}}
          HEROKU_APP_NAME: "comp7940chatbotgg"  # Rename this to the app of your Heroku app.
        run: git push -f https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git main