name: Security vulnerabilities scan and deploy
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Check out main
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

        env:
          DEP_PATH: ./requirements.txt
          HEROKU_API_KEY: ${{secrets.HEROKU_API_KEY}}
          HEROKU_APP_NAME: "comp7940chatbotgg"  # Rename this to the app of your Heroku app.
        run: docker run -dp 3000:3000 Dockerfile
             git push -f https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git main